### PR TITLE
Card fixes

### PR DESCRIPTION
**Pull request by goblin**
WARNING: this PR is based on top of https://github.com/copperdogma/mtgen/pull/9 AND https://github.com/copperdogma/mtgen/pull/10, so they need to be merged first. I can rebase things if needed (the last commit though, "Rename OVM to VMA", will cause a conflict).

Here are various fixes for errors I've found in cards. These came up as I was trying to match up your database with the one on mtgjson.com. Please check the individual commits for detailed descriptions of what I fixed. Feel free to disagree with any of them, just let me know and I'll update the stuff accordingly.

Most notably, the last commit changes the entire set's three-letter code: Vintage Masters is now VMA and not OVM. This may cause issues with code elsewhere.

Also, I'm not sure if those things were autogenerated from something. If so, then we'd need to address those generators instead, and re-generate the jsons.

Lastly, I'd also like to fix up the various UTF-8 encodings of apostrophes and the annoying digraph "Ae", preferably to keep everything as ASCII as possible. But that causes two issues:
* some of the queries might rely on using UTF-8 apostrophes to avoid quoting of '
* most of the mtgjson's database uses "Ae" in titles rather than the UTF-8 equivalent, but not everywhere

So I'm not sure it's worth it at this point. I've added special handling of these in my code. But ideally I think we should fix the data to keep the code as clean as possible. Maybe later.

### CODE REVIEW

**Comment by copperdogma** [comment]
I'm gone for the weekend but I'll work on this (and your other PR) next week. Thanks again.

**Comment by goblin** [comment]
yeah, this one will need some extra care... I think I already screwed up the OVM->VMA rename as it seems the 'ovm' directory is still there ;-) Will probably need to rename "import-exceptions-ovm.json" to "import-exceptions-vma.json" and "import-settings-ovm.json" to "import-settings-vma.json" but I'm not sure where else they're referenced - I'll wait for you to comment before I make further changes, not sure if you'll want that renamed in the first place.

**Comment by goblin** [comment]
I'd be also inclined to rebase this onto current master to get the "Files changed" tab to be more accurate. This would rewrite history though, which is apparently tricky ;-)

**Comment by goblin** [comment]
> I believe these DGM lands WERE supposed to be in there: 

I mean yeah, they were in boosters, but those were "reprints" from RTR or GTC, without the expansion symbol of DGM. At least that's what I understand. So they should probably be included in the same way AER includes lands from KLD...

I may be totally wrong though, I've never played this block, I've just noticed problems when trying to link up against mtgjson.

Many thanks for merging everything! :-)

**Comment by copperdogma** [comment]
Oh I get you now! Sorry! You're totally right. No idea why I re-created these cards as "dgm" when they clearly aren't.

I basically re-did your PR for this plus re-worked the packs.json to import the shocklands from the proper rtr/gtc files (which were already being pulled in anyway).

Thanks for all of your work! I really appreciate it.

**Comment by goblin** [comment]
Excellent, thanks a lot for all your help :-)

**Pull request merged**
