### PR TITLE
prevent too many uncommons in SNC draft booster

### PR DESCRIPTION
**Pull request by mikeMC87**
addresses https://github.com/copperdogma/mtgen/issues/29

### CODE REVIEW

**Comment by mikeMC87** [comment]
@copperdogma I believe this is correct - let me know what you think. Thanks for creating mtgen!

**Review by copperdogma — APPROVED** [review]
Nice work! I don't know what I did there. Copy and paste error, I think. Thanks!

**Comment by copperdogma** [comment]
I've rolled out the fix.

**Comment by mikeMC87** [comment]
awesome, thanks! 🎉

**Pull request merged**
