### PR TITLE
Convert all the set descriptions from .cshtml to .json

### PR DESCRIPTION
**Pull request by goblin**
[As discussed](https://github.com/copperdogma/mtgen/commit/b98e58b0cc4d33069275ff50c4c5384e0331ab1f#commitcomment-20482485) I've converted all the .cshtml files to .json so they can be  easier reused in my [dierk project](https://github.com/goblin/dierk).

You'll still need to add code to load those json files and create proper Models for them (I've never done any ASP.NET so not sure how they all fit in the grander scheme of things).

I've included the hacks I used during the conversion (on the "add all the tools" commit) and then cleaned them up (on the "cleanup" commit).

The format for the JSON file is straightforward. It's an object, containing at least 4 properties: `StartProductName`, `PackFiles`, `CardFiles` and `Updates`. They all correspond with the Set's object properties. `Updates` is an array containing a simple object which always has exactly 2 properties: `UpdateDate` and `HtmlString`. If there are no updates, it contains an empty array. One set, ISD, also contains the optional `CreatedText` string.

Let me know what you think, thanks!

### CODE REVIEW

**Comment by goblin** [comment]
Oh, after the generation, I've also eyeballed all the resulting files and they looked OK - they should contain exactly the same information as the .cshtml files did. Feel free to take a look yourself too if you want.

**Comment by goblin** [comment]
I've removed nvo.json, it seems this set doesn't exist...

**Comment by copperdogma** [comment]
This looks great. I'm working on another branch right now. As soon as I'm done I'll go over your PR. Thanks!

**Comment by copperdogma** [comment]
Now that they've all been converted to json, there's not much sense in leaving them in the /Views/Set/ folder. Would you mind renaming them all to set.json and put them into their respective /wwwroot/[setCode] folders?

Also, would you mind changing the json property names to start with a lowercase letter? That's the standard I've used for the rest of the site.

If you don't have the time just let me know and I'll do it. I really appreciate all of the work!

**Comment by goblin** [comment]
Here you go :-) Let me know if you want me to squash the commits a bit. I guess rewriting history would need a separate PR?

**Comment by copperdogma** [comment]
You're amazing! Thank you so much.

I've merged your changes, modified the C# side to use the new files, and cleaned up a few other things in there while I was at it.

Merged and published!

**Pull request merged**
